services:
  nuxt:
    build:
      context: .
    container_name: nuxt-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/btc
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: btc
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  collector:
    build: ./collector
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/btc
      - COLLECTION_INTERVAL=300000 # 5 минут
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres-data:
